### ISSUE TITLE
Question about pluck

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggspec#7]
Hi @haleyjeppson: do we need `purrr::pluck()` here? To me, it seems to be returning the data-frame itself, but I could be misunderstanding...

https://github.com/vegawidget/ggspec/blob/fbf0f805c824011bb714b83a40c8e50a802ddfa6/R/extract_data.R#L59-L63

If not, I'll take care in my forthcoming PR.

**Comment by haleyjeppson** [comment]
Hi @ijlyttle, yes, I believe you are correct. That must be an artifact from the function's previous form :)

**Comment by ijlyttle** [comment]
I figured, thanks 😁
